### ISSUE TITLE
Application Brainstorming

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/hangashore#1]
This issue will be used to discuss the details of what we want the shoreside application to do.
I will add GUI mockups once I develop them.
### Requirements
- Interface with wireless link to boat (via USB port)
- Parse messages received from boat (Discussed in [boat/issues/3](https://github.com/LakeMaps/boat/issues/3)) and store in a database
- Present information from database as appropriate in an intuitive manner (GUI)
- Interface with an input device (gamepad)
- Have real-time map tracking of the position of the boat. If we re-assemble the GPS and Sonar information in NMEA sentences and put it on a virtual serial port this is easily possible. We can even do real-time tracking/map generation in [Reefmaster](http://reefmaster.com.au/index.php/products/reefmaster).
- Interface paths drawn in mapping software with database for export as a new path to follow (Similar to [Ardupilot Mission Planner](http://ardupilot.org/planner/docs/common-planning-a-mission-with-waypoints-and-events.html))
- Assemble a message for transmission to the boat based on inputs, new paths.
- Provide visualizations for logged data (other than coordinates on a map) such as speed, depth, etc. in the form of graphs.
- Using Wi-fi, be able to SSH into or otherwise connect to the boat (prior to launch) as a means of performing initialization checks after power up.

**Comment by whymarrh** [comment]
> - Parse messages received from boat (Discussed in boat/issues/3) and store in a database
> - Present information from database as appropriate in an intuitive manner (GUI)

These two need clarification, what information in particular?

> - Using Wi-fi, be able to SSH into or otherwise connect to the boat (prior to launch) as a means of performing initialization checks after power up.

How are we planning for this as we'll need some sort of access point somewhere in the system—will it be onshore?

**Comment by arandell93** [comment]
> These two need clarification, what information in particular?

We'll need to store all telemetry in a database. Location, depth and any sensor information. It'd also be useful to store all the control information (Control mode, mode specific information) as well for troubleshooting. 
The GUI needs to present control information and use a sensor view to display sensor info. Location will integrate with map software as discussed. When I do a GUI mockup it will make more sense I think

> How are we planning for this as we'll need some sort of access point somewhere in the system—will it be onshore?

Yes it will be onshore. Something like my wireless router next to the shoreside computer. The Wi-fi on the Pi/laptop will let us access it.
