### ISSUE TITLE
RSSI Readout

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/hangashore#11]
To better understand the current system status and whether or not we are nearing the range limits of the wireless link, we need to display the RSSI of each message received from the Wireless Module on the shoreside application. This information is contained as the fourth- and third-to-last bytes (index 64 and 65) in the response to a receive command from the Wireless Module.

Data is formatted as a 16 bit integer.
Values are always negative.

**Comment by whymarrh** [comment]
[dB vs. dBm](http://www.isa.org/Content/ContentGroups/InTech2/Features/20023/November7/dB_vs__dBm.htm)—what are the units we're working with?

**Comment by arandell93** [comment]
dBm
