### ISSUE TITLE
Initial UI design and mockups

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/hangashore#2]
refs #1

The initial UI needs to designed—we can attach images and whatnot to this issue.

**Comment by arandell93** [comment]
Here's the one I did up last week. Let's use it as a talking point and go from there:

![hangashore gui mockup](https://cloud.githubusercontent.com/assets/10678515/17872978/80962bd4-689d-11e6-9948-f25ceb23f1b4.png)

**Comment by whymarrh** [comment]
If any of those buttons open up a new window, do you want to design those windows as well?

**Comment by arandell93** [comment]
The trends button will open a pretty basic graphing window. I'm not sure what the options are for displaying information via graph are so I'm hesitant to design an image without knowing the capabilities of data presentation (libraries, plugins, software buzz words).
Basically, the goal is something close to this:
- User selects a variable from a list to be on the Y-axis and assigns a colour.
- Multiple variables can be assigned using different colours
- Y-axis limits scale appropriately with the colour of the scale matching the variable it represents
- X-axis defaults to 1 hour but can be scaled as desired
- Graph populates a line in the selected colour showing the history of the variable over the whole x-axis by pulling data from the database.

There are also screens required for error handling and for path-uploading. I'll do up a mock error/alarm screen but I think the path uploading is more a process that we will need to figure out in parallel with development of communications, the graphics are much less important.

**Comment by whymarrh** [comment]
> I'm not sure what the options are for displaying information via graph

✨ Anything is possible ✨

**Comment by arandell93** [comment]
> :sparkles: Anything is possible :sparkles:

Can you give me some examples/names of packages you've used/would like to use?

**Comment by whymarrh** [comment]
I'll have to look into libraries and get back to you

**Comment by arandell93** [comment]
## Updated Home Screen to go with Error Screen

![hangashore gui mockup](https://cloud.githubusercontent.com/assets/10678515/17875085/30e234a4-68aa-11e6-9c57-deef5b80f839.png)

## Error Screen

![hangashore gui mockup errors](https://cloud.githubusercontent.com/assets/10678515/17875036/f8459082-68a9-11e6-95dc-337896475b05.png)

**Comment by whymarrh** [comment]
> I'll have to look into libraries and get back to you

... 2 months later

Was I supposed to look into graphing libraries? If so, for what reason?

Here are two possibilities:
- [Plottable](http://plottablejs.org/components/)
- [MetricsGraphics purports to be for time-series data](http://metricsgraphicsjs.org)

**Comment by arandell93** [comment]
Both look suitable to me. Your choice!

The graphs will be used to trend sensor data over time. Things like temperature, electrical things, speed, etc.

This can in turn be used (either in real-time or afterward doing data-analysis) to help improve our efficiency and quality. For example, we can use a graph of power (voltage x current) vs time to determine how much energy the boat is consuming and then use that information to understand what our range is on a single charge of our batteries. We can then optimize our inputs (path length, desired speed) for whatever we desire and be able to predict how long a path will take us.

**Comment by whymarrh** [comment]
I'm closing this and we can create new, more specific issues for particular UI elements later
