### ISSUE TITLE
Read and Display GPS Data from Boat

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/hangashore#20]
For Rev 1.2, it is required that we have GPS feedback (no control via GPS) implemented such that we are able to transmit the current location of the boat over the wireless link and have it be interpreted and subsequently displayed on the Hangashore application in real time.

As discussed in LakeMaps/boat#18, the parsing of the GPS data from NMEA to something suitable shall be done on the Pi in order to decrease wireless data throughput.

The information to be displayed in text by Hangashore are those referenced in #2:
![image](https://cloud.githubusercontent.com/assets/10678515/22290362/e43b8af0-e2da-11e6-9a1c-40f6d434e55d.png)

Additionally, the position data should be used to present an icon on a map which automatically updates with the position of the boat (and centers the map on that location) and presents a path representing the locations where the boat has been. We will need a trigger to reset the log. I suggest a manual reset button as it offers the most flexibility.

All of the GPS data should be logged with a timestamp each time it is received on the shoreside for review later. This data should not be deleted when the path is reset within the application.

**Comment by whymarrh** [comment]
> The information to be displayed in text by Hangashore are those referenced in #2

Which of those fields are we talking about for Rev 1.2? I am going to assume just longitude and latitude.

**Comment by whymarrh** [comment]
> Additionally, the position data should be used to present an icon on a map which automatically updates with the position of the boat (and centers the map on that location) and presents a path representing the locations where the boat has been. We will need a trigger to reset the log. I suggest a manual reset button as it offers the most flexibility.
>
> All of the GPS data should be logged with a timestamp each time it is received on the shoreside for review later. This data should not be deleted when the path is reset within the application.

This sounds fine, and we'll have this for Rev 1.2, though I would like to hash out the finer details if only to set expectations. The rate at which the boat sends its position updates to the shore will be (relatively) slow—as of right now I am thinking it will be 10 updates per minute. Yes, I chose that number out of the air, but I think we need to expect a decent amount of latency (see also LakeMaps/microcontrollers#7) and also try not to saturate the wireless link*. That said, the map update rate and the accuracy of a path drawn on-screen will not be great. Furthermore, the logs on the shoreside will contain sparse data. We can certainly log data received by Hangashore, but if we choose to do so it will be in addition to logging data on the boat itself.

On the resetting in particular, is this a way to clear the path drawn on the map?

\* Assuming we will want to send or need to send—either in Rev 1.2 or future revisions—more than just position to the shoreside.

**Comment by arandell93** [comment]
> Which of those fields are we talking about for Rev 1.2? I am going to assume just longitude and latitude.

All of them.

> I am thinking it will be 10 updates per minute

That should be a reasonable starting point, if not slightly too infrequent. I would place this as the lower limit on sampling frequency, and foresee an upper limit in the 2-3 per second range. I think it's important that the system is easily modified to change the rate at which we update various metrics though. We will likely want to tune it during testing. Ideally, we would want to be able to drive the boat from Hangashore's location display without it being too impractical. It's important that we don't end up putting ourselves in a position where changes to the sampling rate over the wireless link cause us headaches.

> try not to saturate the wireless link [...] assuming we will want to send or need to send—either in Rev 1.2 or future revisions—more than just position to the shoreside.

We will certainly need to send more information to the shoreside eventually. I think it would be a good idea for us to sit down and discuss what exactly we will eventually have based on our current proposed path forward so we can quantify network traffic and get ahead of any potential bandwidth limitations.

> On the resetting in particular, is this a way to clear the path drawn on the map?

Yes it is just for clearing the current path displayed on the map without deleting the data points from the log. I realize now that my wording was a bit ambiguous.

> [...] in addition to logging data on the boat itself

I assume if we are logging data on the boat it will have a much higher resolution than what we are getting on the shoreside? Further, will that information be easily transferable over the WiFi link we are adding in?

**Comment by whymarrh** [comment]
> I assume if we are logging data on the boat it will have a much higher resolution than what we are getting on the shoreside? Further, will that information be easily transferable over the WiFi link we are adding in?

Yes on both counts.

**Comment by arandell93** [comment]
![image](https://cloud.githubusercontent.com/assets/10678515/22356621/497176c2-e40d-11e6-8463-8eea82b29ca8.png)

**Comment by whymarrh** [comment]
That said, the update rate is a larger discussion that may require a bit more context and/or planning (like you said, we may need to map out what our communications will look like in the coming revisions). The ability to update the communication rate on-the-fly isn't in scope for Rev 1.2 (unless we want to make it so?) but we will certainly be able to adjust the rate when the boat is on the shore. Additionally, where the boat has its data, be it GPS or anything, in the highest resolution possible locally, we can always opt to visualize the data post-mission should we need that detail.

**Comment by arandell93** [comment]
> we will certainly be able to adjust the rate when the boat is on the shore

This is all I think we will need for now. In the future if longer range is required as the boat moves further away mid-mission, we should be able to switch during a mission but that is outside the scope of 1.2

**Comment by whymarrh** [comment]
> Additionally, the position data should be used to present an icon on a map which automatically updates with the position of the boat (and centers the map on that location) and presents a path representing the locations where the boat has been. We will need a trigger to reset the log. I suggest a manual reset button as it offers the most flexibility.
>
> All of the GPS data should be logged with a timestamp each time it is received on the shoreside for review later. This data should not be deleted when the path is reset within the application.

A few of those finer details are still unimplemented, but I'll open new issues for those.

I think I'm good to close this now that #44 is merged into `master`.
