### ISSUE TITLE
Add settings screen

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/hangashore#22]
We'll need a setting screen to facilitate configuration of the application.

Possible settings:

- [x] USB port that the wireless microcontroller is connected to (#14)
- [x] Map source (and API key if needed)
- [x] Log directory (where to store log files)
- ???

**Comment by arandell93** [comment]
A couple more. Delete if these aren't needed. Discussion of some settings likely required to determine if it's needed.

- [x] USB port that Controller is connected to
- [x] Map source

**Comment by whymarrh** [comment]
The USB port that the controller is connected to is [magically](https://media.giphy.com/media/VHngktboAlxHW/giphy.gif) detected, so we won't need one for that.

**Comment by whymarrh** [comment]
I've added map source to the OP (as those are the only checkboxes that matter on GitHub).

**Comment by whymarrh** [comment]
For the time being, the application will store its logs internally (#28). We can add a UI for exploring the logs or once we have a log output directory we can store a log file.

**Comment by whymarrh** [comment]
This and #14 block #15.
