### ISSUE TITLE
Wireless module + MCP2210 communication brainstorming

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/hangashore#3]
Datasheets:
- [RFM69HCW ISM Transceiver Module v1.1](https://cdn.sparkfun.com/datasheets/Wireless/General/RFM69HCW-V1.1.pdf)
- [MCP2210 USB-to-SPI Protocol Converter with GPIO (Master Mode)](http://www.microchip.com/wwwproducts/en/MCP2210)

**Comment by arandell93** [comment]
I skimmed the 2210 Manual looking for what I think are relevant for progressing the work:
- The default SPI parameters (found on page 4) are
  - Speed; 1Mbit/s
  - Packet: 4 bytes per transaction
  - GP1 used as chip select
- The NVRAM can be modified to change the configuration of the chip. These modifications can be performed through the provided MCP2210 Utility application (Details on page 9, download [here](http://ww1.microchip.com/downloads/en/DeviceDoc/MCP2210Utility_v1.2.2.zip))
- Pages 54-55 of the detail the message structure for sending SPI.

The MCP2210 Utility seems to be fairly straightforward. I installed and opened it up to see what it gave me. It looks like you can do all the configuration required from there.
![image](https://cloud.githubusercontent.com/assets/10678515/19531688/1f0aaacc-9613-11e6-8da8-9343e2326ae4.png)

When I selected 'Load Factory Default Settings' under 'File' I got this:
![image](https://cloud.githubusercontent.com/assets/10678515/19531717/3e37cd6c-9613-11e6-88e9-a325faee12fd.png)

You can use the 'Operations' tab to attempt to connect to devices with known names/addresses:
![image](https://cloud.githubusercontent.com/assets/10678515/19531751/6e82dffc-9613-11e6-9301-4872daf59c02.png)

There are a couple other options that I assume become available once a device is plugged in, but I don't have one to test with currently:
![image](https://cloud.githubusercontent.com/assets/10678515/19531797/94b970fa-9613-11e6-8f36-c62a4aaea479.png)

The 'Chip Access' tab doesn't appear to have much in terms of actually sending the messages:
![image](https://cloud.githubusercontent.com/assets/10678515/19531852/c6ab5cae-9613-11e6-8ade-a9a2baf163e0.png)

I'm not sure exactly how you go about sending /receiving messages once the chip is configured, but there is another application (Command Line Interface) on [MCP's product page](http://www.microchip.com/wwwproducts/en/MCP2210) that looks to have a series of commands, one of them appears to be an SPI send command.
I can't get it to stay open when I try to run it; perhaps because I don't have a valid device connected or there are driver issues; but for the brief time the window pops up I see this:
![image](https://cloud.githubusercontent.com/assets/10678515/19531962/48405738-9614-11e6-9ef3-f4e2bfc5e507.png)

**Comment by whymarrh** [comment]
Possibly useful: [RFM69HCW Hookup Guide](https://learn.sparkfun.com/tutorials/rfm69hcw-hookup-guide)

**Comment by whymarrh** [comment]
This is me trying to understand the procedure from the Arduino code in that walkthrough.

Building blocks:

``` arduino
// select the RFM69 transceiver (save SPI settings, set CS low)
void RFM69::select() {
    noInterrupts();
    // set RFM69 SPI settings
    SPI.setDataMode(SPI_MODE0);
    SPI.setBitOrder(MSBFIRST);
    digitalWrite(_slaveSelectPin, LOW);
}

// unselect the RFM69 transceiver (set CS high, restore SPI settings)
void RFM69::unselect() {
    digitalWrite(_slaveSelectPin, HIGH);
    interrupts();
}

uint8_t RFM69::readReg(uint8_t addr)
{
    select();
    SPI.transfer(addr & 0x7F);
    uint8_t regval = SPI.transfer(0);
    unselect();
    return regval;
}

void RFM69::writeReg(uint8_t addr, uint8_t value)
{
    select();
    SPI.transfer(addr | 0x80);
    SPI.transfer(value);
    unselect();
}
```

The high-level procedure:

``` arduino
RFM69 radio;
radio.initialize(FREQUENCY, MYNODEID, NETWORKID);
radio.setHighPower(true); // Always use this for RFM69HCW
radio.send(TONODEID, sendbuffer, sendlength);
```

That same procedure inlined:

``` arduino
// => radio.initialize(FREQUENCY, MYNODEID, NETWORKID);
digitalWrite(_slaveSelectPin, HIGH);
pinMode(_slaveSelectPin, OUTPUT);
SPI.begin();
unsigned long start = millis();
uint8_t timeout = 50;
do
    writeReg(REG_SYNCVALUE1, 0xAA);
while (readReg(REG_SYNCVALUE1) != 0xaa && (millis() - start) < timeout);
start = millis();
do
    writeReg(REG_SYNCVALUE1, 0x55);
while (readReg(REG_SYNCVALUE1) != 0x55 && (millis() - start) < timeout);

for (uint8_t i = 0; CONFIG[i][0] != 255; i++)
    writeReg(CONFIG[i][0], CONFIG[i][1]);

// Disable encryption during initialization so we always start from a known state
writeReg(REG_OPMODE, (readReg(REG_OPMODE) & 0xE3) | RF_OPMODE_STANDBY);
writeReg(REG_PACKETCONFIG2, (readReg(REG_PACKETCONFIG2) & 0xFE) | (key ? 1 : 0));

// => radio.setHighPower(true); // Always use this for RFM69HCW
writeReg(REG_OCP, true ? RF_OCP_OFF : RF_OCP_ON);
// enable P1 & P2 amplifier stages
writeReg(REG_PALEVEL, (readReg(REG_PALEVEL) & 0x1F) | RF_PALEVEL_PA1_ON | RF_PALEVEL_PA2_ON);

writeReg(REG_OPMODE, (readReg(REG_OPMODE) & 0xE3) | RF_OPMODE_STANDBY);
start = millis();
// wait for ModeReady
while (
       ((readReg(REG_IRQFLAGS1) & RF_IRQFLAGS1_MODEREADY) == 0x00)
    && (millis() - start) < timeout
);
if ((millis() - start) >= timeout)
    return false;
attachInterrupt(_interruptNum, RFM69::isr0, RISING);

// => radio.send(TONODEID, sendbuffer, sendlength);
// avoid RX deadlocks
writeReg(REG_PACKETCONFIG2, (readReg(REG_PACKETCONFIG2) & 0xFB) | RF_PACKET2_RXRESTART);
uint32_t now = millis();
while (!canSend() && (millis() - now) < RF69_CSMA_LIMIT_MS) receiveDone();
// => sendFrame(toAddress, buffer, bufferSize, requestACK, false);
// turn off receiver to prevent reception while filling fifo
writeReg(REG_OPMODE, (readReg(REG_OPMODE) & 0xE3) | RF_OPMODE_STANDBY);
// wait for ModeReady
while ((readReg(REG_IRQFLAGS1) & RF_IRQFLAGS1_MODEREADY) == 0x00);
writeReg(REG_DIOMAPPING1, RF_DIOMAPPING1_DIO0_00); // DIO0 is "Packet Sent"
if (bufferSize > RF69_MAX_DATA_LEN)
    bufferSize = RF69_MAX_DATA_LEN;
// control byte
uint8_t CTLbyte = 0x00;
// write to FIFO
select();
SPI.transfer(REG_FIFO | 0x80);
SPI.transfer(bufferSize + 3);
SPI.transfer(toAddress);
SPI.transfer(_address);
SPI.transfer(CTLbyte);

for (uint8_t i = 0; i < bufferSize; i++)
    SPI.transfer(((uint8_t*) buffer)[i]);
unselect();
// no need to wait for transmit mode to be ready since its handled by the radio
writeReg(REG_OPMODE, (readReg(REG_OPMODE) & 0xE3) | RF_OPMODE_TRANSMITTER);
// => setHighPowerRegs(true);
writeReg(REG_TESTPA1, true ? 0x5D : 0x55);
writeReg(REG_TESTPA2, true ? 0x7C : 0x70);
uint32_t txStart = millis();
// wait for DIO0 to turn HIGH signalling transmission finish
while (digitalRead(_interruptPin) == 0 && (millis() - txStart) < RF69_TX_LIMIT_MS);
writeReg(REG_OPMODE, (readReg(REG_OPMODE) & 0xE3) | RF_OPMODE_STANDBY);
```

---

Arduino references:
- [`attachInterrupts()`](https://www.arduino.cc/en/Reference/AttachInterrupt)
- [`interrupts()`](https://www.arduino.cc/en/Reference/Interrupts)
- [`noInterrupts()`](https://www.arduino.cc/en/Reference/NoInterrupts)
- [`SPI#begin()`](https://www.arduino.cc/en/Reference/SPIBegin)
- [`SPI#transfer(byte val)`](https://www.arduino.cc/en/Reference/SPITransfer)

**Comment by whymarrh** [comment]
Does the MCP2210 drive the slave select pin?

**Comment by whymarrh** [comment]
It sounds like slave select is done via GPIO (and LakeMaps/Dartmouth#2 seems to agree).

@FifoIronton or @arandell93—what pin am I looking to use?

**Comment by arandell93** [comment]
> Does the MCP2210 drive the slave select pin?

Yes. So the functions `void RFM69::select()` and `void RFM69::unselect()` manage the chip select (CS) pin  via the Arduino. For us, this is something we do in the config (see my earlier post referencing the config utility) for the MCP2210.

> @FifoIronton or @arandell93—what pin am I looking to use?

The MCP2210 has a bunch of GPIO that you use as CS pins, enabling multiple slave nodes to be managed by a single MCP2210. In our case, we only have one slave device so we don't need to be setting and unsetting several CS every time we want to send a message. We simply set it once and forget it. By default, GPIO 1 is enabled as a chip select. The GPIO pin we will have to use as a CS on the MCP2210 is dictated by the way the PCB was designed.
@FifoIronton what pin on the MCP2210 is tied to the slave select input pin (5) on the RFM69HCW? Post a screen shot of the schematic for us please.
![image](https://cloud.githubusercontent.com/assets/10678515/19597733/eb7e537a-9770-11e6-9553-f2a31898e5d4.png)

**Comment by whymarrh** [comment]
From the looks of it, `GP6` (GPIO 6?) is routed to the `SS_0`/`NSS`.

Cranberry board PCB schematic:

![Cranberry board PCB schematic](https://cloud.githubusercontent.com/assets/1623628/19613009/743ff9a4-97c4-11e6-8f3d-2abfb42f7c5a.png)

**Comment by whymarrh** [comment]
The applications from Microchip recognize the device, which is good. The utility doesn't offer much, but they have an SPI terminal which may be a useful debugging tool. I don't yet know how to use it, and sending `0xAF`+`0xAA` (a write to register `0x2F`) followed by `0x2F`+`0x00` (a read of register `0x2F`) doesn't seem to work—it's possible, even likely, that I have the values wrong, but at least this is a way for us to test out the RFM69HCW through the MCP2210.

![MCP2210 Utility](https://cloud.githubusercontent.com/assets/1623628/19623987/2f3aed2e-98bd-11e6-911a-e7bd9cc01966.png)

![SPI Terminal](https://cloud.githubusercontent.com/assets/1623628/19623986/2f33c9b8-98bd-11e6-9436-d2f8e4bd4732.png)

**Comment by arandell93** [comment]
I notice you've got all of the GP IO pins set as chip select and set to HIGH in both idle and active except GP 6 which is set to 0 on idle and 1 on active. This seems to be backwards from the required (should be idle high and active low) configuration based on page 44 of the [RFM69HCW Manual](https://cdn.sparkfun.com/datasheets/Wireless/General/RFM69HCW-V1.1.pdf)
![image](https://cloud.githubusercontent.com/assets/10678515/19627709/e373f23a-9927-11e6-9272-bda98ffaa965.png)

It should also be noted that this doesn't mean you should set all the other GP pins on the MCP2210 to high, and certainly not to chip-select mode. Keep in mind all those pins are tied to various pins on the 69HCW (so you could be inhibiting the 69HCW in some other way).
In particular, note in the schematic above that GP7 is connected to the 69HCW's reset pin.

My recommendation would be to configure all other GP on the 2210 as GPIO and in particular confirm the function of the HCW reset pin. From p. 75-76 of the [RFM69HCW Manual](https://cdn.sparkfun.com/datasheets/Wireless/General/RFM69HCW-V1.1.pdf):

> 7.2. Reset of the Module
> A power-on reset of the RFM69HCW is triggered at power up. Additionally, a manual reset can be issued by controlling pin RESET.
> 7.2.1. POR
> If the application requires the disconnection of VDD from the RFM69HCW, despite of the extremely low Sleep Mode current, the user should wait for 10 ms from of the end of the POR cycle before commencing communications over the SPI bus. **Pin 6 (Reset) should be left floating during the POR sequence.**
> 7.2.2. Manual Reset
> A manual reset of the RFM69HCW is possible even for applications in which VDD cannot be physically disconnected. **Pin RESET should be pulled high for a hundred microseconds, and then released**. The user should then wait for 5 ms before using the module.

By configuring all of the not-used GPIO pins (all but 6) on the 2210 as GPIO and setting them to input mode (I am assuming this is possible, as you always have to specify the logic direction on IO pins) we should be able to fulfill the requirement that Pin 7 (connected to RESET) needs to be left floating during the power-up sequence reset of the 69HCW. Leaving the pin as an input will mean we can't reset the wireless module on the fly, so perhaps we can change it to output with active high logic on the fly if a reset is required? Either way, for the immediate goal of getting it working I recommend leaving it as an input. We can manually power cycle whole PCB if we need to reset.

**Comment by whymarrh** [comment]
> > **Pin 6 (Reset) should be left floating during the POR sequence.**

Floating in this context means what?

**Comment by arandell93** [comment]
Floating refers to the pin being essentially open-circuited; there is not path for current to flow and therefore since the RESET pin is an input it is essentially an isolated circuit. If the other side of the wire is either high or low, it will force the RESET pin to read either high or low. 
In order to avoid this we have to 'disconnect' the reset pin from any circuits. This can be accomplished by configuring the other side (Pin 7 on the 2210) as an input as opposed to an output.
From the [Wikipedia  article on Floating Ground](https://en.wikipedia.org/wiki/Floating_ground):

> Conductors are also described as having a floating voltage if they are not connected electrically to another non-floating conductor. Without such a connection, voltages and current flows are induced by electromagnetic fields or charge accumulation within the conductor rather than being due to the usual external potential difference of a power source.

**Comment by whymarrh** [comment]
Hmm, ok. I guess I don't understand what you mean by setting Pin 7 as an input (and re-reading your previous comment, maybe it isn't possible?). This is what I have:

![SPI Terminal](https://cloud.githubusercontent.com/assets/1623628/19629290/2891c832-994c-11e6-9cb6-c0e2f30556cc.png)

**Comment by arandell93** [comment]
I am not sure, but it looks like the GP Designation register is likely the control for GP direction (Input vs output).
![image](https://cloud.githubusercontent.com/assets/10678515/19629306/88e6789a-994c-11e6-8ea4-16a29d48d3c7.png)
Does the software come with a manual?

**Comment by whymarrh** [comment]
> Does the software come with a manual?

It does not

**Comment by arandell93** [comment]
Perhaps the MCP2210 manual has something to say about controlling the config of the GPIO? More than being an input, we could get away with just not initializing the pins so that they are left floating.

**Comment by arandell93** [comment]
So I found in the [MCP2210 Manual](http://ww1.microchip.com/downloads/en/DeviceDoc/22288A.pdf) that you are able to control the GPIO direction in a register in the NVRAM but it is not the GP Designation register as I thought:
![image](https://cloud.githubusercontent.com/assets/10678515/19643214/bcae60a8-99c3-11e6-9c1b-c57aa277fef2.png)

Here's the info in the table related to changing the settings (page 46/47).
![image](https://cloud.githubusercontent.com/assets/10678515/19644232/347f6c6c-99c9-11e6-8b26-d6c00b4a741e.png)
You can use the command line application to read/write the registers directly via communications over USB if you are unable to do it from the GUI application.
I am not sure whether a 0 represents an input or an output, so you will have to mess around with it a bit to figure that out.

**Comment by arandell93** [comment]
That is what that shows. I just wanted to make sure it is the most updated
schematic. If it is we are good to configure the MCP 2210.

**Comment by arandell93** [comment]
Good Riddance
