### ISSUE TITLE
Add a deadzone to gamepad input

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/hangashore#31]
Currently the gamepad input is raw and without a deadzone. Apparently this is "literally unusable."

Possible deadzone implementations include axial (independent axes) or radial (circular):

> You will generally want to use `IndependentAxes` mode for things where the X and Y stick positions control unrelated game values. For instance steering a car is independent of accelerating and braking, or moving up and down through a menu is independent of moving left and right. The `Circular` mode works better for things where the stick input is used to choose a location on a 2D plane, such as aiming a weapon or moving the character in a Mario64 style platformer.
> — [Gamepads suck](https://blogs.msdn.microsoft.com/shawnhar/2007/03/28/gamepads-suck/)

**Comment by whymarrh** [comment]
Refs: [Gamepads suck](https://blogs.msdn.microsoft.com/shawnhar/2007/03/28/gamepads-suck/) and [Doing Thumbstick Dead Zones Right](http://www.third-helix.com/2013/04/12/doing-thumbstick-dead-zones-right.html)

**Comment by arandell93** [comment]
> in a Mario64 style platformer

Is it too late to turn the boat project into a Mario64 style platformer?
