### ISSUE TITLE
Develop Timestamp and Wireless Receive Functionality

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/hangashore#32]
Refs LakeMaps/boat#51 and LakeMaps/boat#47

Hanagashore needs to be able to timestamp when it sends a message out over the wireless link (immediately before it sends a Transmit Command) and then receive the same message back in a 'loopback' test using the wireless Receive Command. Once the data is received and compared to confirm it is the same as what was sent, a new timestamp should be marked.

**Comment by whymarrh** [comment]
I've updated the OP to fix the references ([the format is `Username/Repository#`](https://help.github.com/articles/autolinked-references-and-urls/#issues-and-pull-requests)).

**Comment by whymarrh** [comment]
I'm closing this—we can reopen this issue when it's needed.
