### ISSUE TITLE
Coordinate Shoreside Input-Output Polling to Optimize Wireless Link Rate

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/hangashore#33]
We have been experiencing a backlog of gamepad inputs sent to the wireless module on rotation of thumb stick.

Shoreside is sending data to wireless link as fast as it reads joystick (16 ms). Sending data to wireless module is slower than that therefore it is bottlenecking. Confirmed by viewing that TX/RX lights on shoreside arduino remained flashing after joystick inputs stopped.

The solution to this appears to be to slow the rate at which we are sending to the wireless module (recommend 30 ms based on boat software) and only take gamepad data to send to module at those intervals, discarding all other gamepad data. However, gamepad polling is to remain the same for future expansion.

**Comment by whymarrh** [comment]
Note to self: it would be neat if the wireless driver dropped all motion values received during send.

**Comment by whymarrh** [comment]
This interacts with #31+#34 in an interesting way. If we choose to drop values during send to fix this backlog, we risk dropping the zero values and negating the work to add a deadzone to the gamepad.
