### ISSUE TITLE
Deployment Method for Hangashore

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/hangashore#58]
We need to decide upon a way we can deploy the shoreside application to any devices that may want to use it. Since our app will not be in the app store/google play store, we will have to sideload it.

I have a suggestion for this which makes it so that we don't need an internet connection (in instances such as where someone shows up to a survey without the latest version). We can have the Pi host the files (ftp style?) for download via our wireless network. The person would use their device and connect via browser to a landing page from which they can have access to the required files, download them and install them.

Thoughts?

**Comment by whymarrh** [comment]
> I have a suggestion for this which makes it so that we don't need an internet connection (in instances such as where someone shows up to a survey without the latest version). We can have the Pi host the files (FTP style?) for download via our wireless network. The person would use their device and connect via browser to a landing page from which they can have access to the required files, download them and install them.

Something like this may work for Android devices but iOS devices cannot sideload on the fly.

**Comment by whymarrh** [comment]
For iOS devices we will need to build and sideload the application from a Mac with Xcode running on it.

**Comment by arandell93** [comment]
> For iOS devices we will need to build and sideload the application from a Mac with Xcode running on it

That issue requires the `make this less dumb` label.

**Comment by whymarrh** [comment]
I'll close this for now—we can revisit deployment once there are tangible iOS or Android versions
