### ISSUE TITLE
Basemaps issues

### ISSUE THREAD

**Issue by whymarrh** [LakeMaps/hangashore#66]
How bad are our basemaps? Where can we get better basemaps?

**Comment by arandell93** [comment]
> How bad are our basemaps?

Bad.

> Where can we get better basemaps?

[SASPlanet](https://www.openhub.net/p/sasplanet) has links to the source of tiles for all the maps they use. For example, some of the better ones are:

- [Bing Satellite](http://ecn.t0.tiles.virtualearth.net/tiles/a)
- [Arc GIS Satellite](http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/)
- [Nokia Here.com Satellite](http://1.maps.nlp.nokia.com/maptile/2.1/maptile/newest/satellite.day/)

**Comment by whymarrh** [comment]
[This is the correct link for the world imagery service (ArcGIS)](http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/)

**Comment by whymarrh** [comment]
> For example, some of the better ones are:

How can we go about comparing these in some structured way?

**Comment by arandell93** [comment]
> How can we go about comparing these in some structured way?

What do you mean by structured? I don't think there is a statistical way to determine which is better, as they vary in coverage and age a lot. The best imagery varies widely by location for the most part, and it depends on what you're looking for. I've spent a lot of time looking at any and all imagery I can get my hands on so I have a pretty good idea of what makes something suitable to use for our purposes.

**Comment by whymarrh** [comment]
It's worth looking into [Mapbox's basemaps](https://www.mapbox.com/api-documentation/#maps):

> - [`mapbox.streets`](http://api.mapbox.com/v4/mapbox.streets.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.light`](http://api.mapbox.com/v4/mapbox.light.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.dark`](http://api.mapbox.com/v4/mapbox.dark.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.satellite`](http://api.mapbox.com/v4/mapbox.satellite.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.streets-satellite`](http://api.mapbox.com/v4/mapbox.streets-satellite.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.wheatpaste`](http://api.mapbox.com/v4/mapbox.wheatpaste.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.streets-basic`](http://api.mapbox.com/v4/mapbox.streets-basic.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.comic`](http://api.mapbox.com/v4/mapbox.comic.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.outdoors`](http://api.mapbox.com/v4/mapbox.outdoors.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.run-bike-hike`](http://api.mapbox.com/v4/mapbox.run-bike-hike.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.pencil`](http://api.mapbox.com/v4/mapbox.pencil.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.pirates`](http://api.mapbox.com/v4/mapbox.pirates.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.emerald`](http://api.mapbox.com/v4/mapbox.emerald.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)
> - [`mapbox.high-contrast`](http://api.mapbox.com/v4/mapbox.high-contrast.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#3/0.00/0.00)

Note that some (read: most) of these are simply style variation of the same underlying OSM data but there may be visual tweaking that's useful. The satellite imagery might be good.

**Comment by arandell93** [comment]
The sat imagery (at least in the area around my cabin) is black and white and several years old. I can't judge the other areas but it is largely colour at the lowest level and fairly high resolution so it could work. It looks like at least some of these sets are from ESRI but are not the most up to date.

I'm not sure what the deal is for using ESRI's maps. They're by far the best I've seen.

**Comment by whymarrh** [comment]
I think I'm going to close this for now, we can reopen it if the need arises. We're going to continue to default to OSM (or whatever we're using) and build in the option to import local map tiles should the user have some laying around from a more detailed source.
