### ISSUE TITLE
Source of Map for Realtime Tracking

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/hangashore#7]
I'm not sure if this has been addressed, nor how difficult it is to implement, but the Hangashore application needs to pull its map from a local location, as we will not have internet access.

[SAS Planet](https://www.openhub.net/p/sasplanet) is what I use for obtaining offline maps, as you can select any online data source (Google Maps, Earth, Bing Maps, ArcGIS, OpenMap, etc.) and it simply caches everything that you load. You can specify an area and download the full tile set as well.

It's an open project, so perhaps there is a way to interface it with our GUI? If not it can certainly be a good place for obtaining files for offline use.

**Comment by whymarrh** [comment]
I'm not familiar with SAS Planet so I will need to look into it. That said, initially (i.e. the map added in #6) uses [Leaflet](http://leafletjs.com), which is tile based and pulls its tiles from some online server (e.g. OSM). What we can/will do is cache the tiles locally.

**Comment by arandell93** [comment]
Okay makes sense! It's definitely worth investigating SAS Planet or at least something with aerial imagery, because I know a lot of times small bodies of water are left out of more traditional maps.

**Comment by whymarrh** [comment]
I agree that aerial imagery will be important and we can look into better sources eventually. That said, a lot of great basemaps sources come with conditions (e.g. are non-free or [require authentication](https://msdn.microsoft.com/en-us/library/mt712556.aspx)). I'm going to close this for now where rev. 1 is focusing on RC and we can revisit this next revision or later.
